routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CareerController;
use App\Http\Controllers\Admin\EventsController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\Main\DictionaryController;
use App\Http\Controllers\Main\EventController;
use App\Http\Controllers\Main\LoginController;
use App\Http\Controllers\Main\MainController;
use App\Http\Controllers\Main\ProjectsController;
use Illuminate\Support\Facades\Route;


Route::get('/', [MainController::class, 'main']);

Route::get('/lang/{lang}', [LocalizationController::class, 'index'])->name('lang-switch');

//Route::middleware(['auth:sanctum', 'verified', 'prefix' => 'admin'])->group(function (){
//
//});
Route::post('/ckeditor-upload-file', [\App\Http\Controllers\CKEditorController::class, 'upload'])->name('ckeditor.image-upload');
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth:sanctum'], function () {
    Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
    #region Menu
    Route::get('/menu', [MenuController::class, 'index'])->name('menu-index');
    Route::get('/menu/create', [MenuController::class, 'create'])->name('menu-create');
    Route::post('/menu/create', [MenuController::class, 'store'])->name('menu-store');
    Route::get('/menu/{menu}/update', [MenuController::class, 'updateForm'])->name('menu-update-form');
    Route::post('/menu/{menu}/update', [MenuController::class, 'update'])->name('menu-update');
    Route::delete('/menu/{menu}/delete', [MenuController::class, 'delete'])->name('menu-delete');
    Route::post('/menu/rearrange', [MenuController::class, 'rearrange'])->name('menu-rearrange');
    #endregion

    #region News
    Route::get('/news', [NewsController::class, 'index'])->name('news-index');
    Route::get('/news/create', [NewsController::class, 'create'])->name('news-create');
    Route::post('/news/create', [NewsController::class, 'store'])->name('news-store');

    Route::post('/news/{news}/delete', [NewsController::class, 'delete']);

    Route::get('/news/{news}/update', [NewsController::class, 'updateForm'])->name('news-update-form');
    Route::post('/news/{news}/update', [NewsController::class, 'update'])->name('news-update');
    Route::get('/news/{news}', [NewsController::class, 'show'])->name('news-show');
    #endregion

    #region Events
    Route::get('/events', [EventsController::class, 'index'])->name('events-index');
    Route::get('/events/create', [EventsController::class, 'create'])->name('events-create');
    Route::post('/events/create', [EventsController::class, 'store'])->name('events-store');

    Route::post('/events/{events}/delete', [EventsController::class, 'delete'])->name('events-delete');

    Route::get('/events/{events}/update', [EventsController::class, 'updateForm'])->name('events-update-form');
    Route::post('/events/{events}/update', [EventsController::class, 'update'])->name('events-update');
    Route::get('/events/{events}', [EventsController::class, 'show'])->name('events-show');
    #endregion

    #region Dictionary
    Route::get('/dictionary', [\App\Http\Controllers\Admin\DictionaryController::class, 'index'])->name('dictionary-index');
    Route::get('/dictionary/create', [\App\Http\Controllers\Admin\DictionaryController::class, 'create'])->name('dictionary-create');
    Route::post('/dictionary/create', [\App\Http\Controllers\Admin\DictionaryController::class, 'store'])->name('dictionary-store');

    Route::post('/dictionary/{dictionary}/delete', [\App\Http\Controllers\Admin\DictionaryController::class, 'delete']);

    Route::get('/dictionary/{dictionary}/update', [\App\Http\Controllers\Admin\DictionaryController::class, 'updateForm'])->name('dictionary-update-form');
    Route::post('/dictionary/{dictionary}/update', [\App\Http\Controllers\Admin\DictionaryController::class, 'update'])->name('dictionary-update');
    Route::get('/dictionary/{dictionary}', [\App\Http\Controllers\Admin\DictionaryController::class, 'show'])->name('dictionary-show');
    #endregion

    #region Career
    Route::get('/career-group', [CareerController::class, 'groupIndex'])->name('career-group-index');
    Route::get('/career-group/create', [CareerController::class, 'groupCreate'])->name('career-group-create');
    Route::post('/career-group/create', [CareerController::class, 'groupStore'])->name('career-group-store');

    Route::post('/career-group/{model}/delete', [CareerController::class, 'groupDelete'])->name('career-group-delete');

    Route::get('/career-group/{model}/update', [CareerController::class, 'groupUpdateForm'])->name('career-group-update-form');
    Route::post('/career-group/{model}/update', [CareerController::class, 'groupUpdate'])->name('career-group-update');

    Route::get('/career/{group}', [CareerController::class, 'index'])->name('career-index');
    Route::get('/career/create/{group}', [CareerController::class, 'create'])->name('career-create');
    Route::post('/career/create', [CareerController::class, 'store'])->name('career-store');
    Route::get('/career/{career}/update', [CareerController::class, 'updateForm'])->name('career-update-form');
    Route::post('/career/{career}/update', [CareerController::class, 'update'])->name('career-update');
    Route::delete('/career/{career}/delete', [CareerController::class, 'delete'])->name('career-delete');
    Route::post('/career/rearrange', [CareerController::class, 'rearrange'])->name('career-rearrange');
    #endregion
});

Route::name('main-')->group(function (){
    Route::get('/career', [MainController::class, 'career'])->name('career');
    Route::get('/get-career/{career}', [MainController::class, 'getCareer'])->name('get-career');
    Route::get('/cert/{user}/{course}', [MainController::class, 'cert'])->name('cert');
    Route::get('/news', [\App\Http\Controllers\Main\NewsController::class, 'index'])->name('news-index');
    Route::get('/news/{news}', [\App\Http\Controllers\Main\NewsController::class, 'show'])->name('news-show');
    Route::get('/tourist_atlas', [ProjectsController::class, 'atlas'])->name('tourist_atlas');
    Route::get('/events', [EventController::class, 'index'])->name('events-index');
    Route::get('/events/{event}', [EventController::class, 'show'])->name('events-show');
    Route::get('/tour_dictionary', [DictionaryController::class, 'index'])->name('dictionary-index');
    Route::get('/tour_dictionary/{dictionary}', [DictionaryController::class, 'show'])->name('dictionary-show');
    Route::get('/login-register', function (){
        return view('login-register');
    })->name('login-register');
    Route::post('/auth-check', [LoginController::class, 'check'])->name('auth-check');
    Route::post('/auth-register', [LoginController::class, 'register'])->name('auth-register');
    Route::get('/wait-moderator', function (){
        return view('wait-moderator');
    })->name('wait-moderator');
});

include 'academy.php';

Route::get('/{slug}', [MainController::class, 'generate']);

app/Http/Controllers/Academy/Instructor/MainController.php
<?php


namespace App\Http\Controllers\Academy\Instructor;


use App\Http\Controllers\Controller;
use Request;

class MainController extends Controller
{
    public function dashboard()
    {
        return view('academy.instructor.main', [] );
    }

}

app/Http/Controllers/Academy/Student/MainController.php
<?php


namespace App\Http\Controllers\Academy\Student;


use App\Http\Controllers\Controller;
use App\Http\Services\GenerateCertificateService;
use App\Models\Courses;
use Request;

class MainController extends Controller
{
    public function dashboard()
    {
        return redirect()->route('student-courses');
        return view('academy.student.main', []);
    }

    public function certs()
    {
        return view('academy.student.cert.cert', [
            'model' => auth()->user()->coursesCompleted
        ]);
    }

    public function downloadCerts(Courses $courses)
    {
        $headers = [
            'Content-Type' => 'image/jpeg',
        ];
        $file = public_path('certificates/' . auth()->user()->id . '/' . $courses->id . '/' . $courses->getName() . '.jpg');
        return response()->download($file, $courses->getName(). '.jpg', $headers);
    }
}

app/Http/Controllers/Main/DictionaryController.php
<?php


namespace App\Http\Controllers\Main;


use App\Http\Controllers\Controller;
use App\Models\Dictionary;

class DictionaryController extends Controller
{
    public function index()
    {
        return view('Main.dictionary.index', [
            'count' => Dictionary::count()
        ]);
    }

    public function show(Dictionary $dictionary)
    {
        return view('Main.dictionary.show', [
            'model' => $dictionary
        ]);
    }

}

app/Http/Controllers/Main/EventController.php
<?php


namespace App\Http\Controllers\Main;


use App;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class EventController extends Controller
{
    public function index(Request $request)
    {
        $events = App\Models\Events::whereYear('start_date', date('Y'))
            ->where([
                ['active', true],
                ['name_' . App::getLocale(), '!=', null],
            ])->orderBy('start_date')->get()->groupBy(function ($d) {
                return Carbon::parse($d->start_date)->format('m');
            });
        return view('Main.events.index', [
            'model' => $events
        ]);
    }

    public function show(Request $request, App\Models\Events $event)
    {
        $events = App\Models\Events::whereYear('created_at', date('Y'))
            ->where([
                ['active', true],
                ['name_' . App::getLocale(), '!=', null],
//                ['start_date', '>', now()],
                ['id', '!=', $event->id]
            ])->limit(4)->get();
        $event->views = $event->views + 1;
        $event->save();
        return view('Main.events.show', [
            'event' => $event,
            'otherEvents' => $events
        ]);
    }

}

app/Http/Controllers/Main/LoginController.php
<?php


namespace App\Http\Controllers\Main;


use App;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Authenticatable;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class LoginController extends Controller
{
    use Authenticatable;

    public function register(Request $request){
        $input = $request->all();

        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'min:6|required_with:password_confirmation|same:password_confirmation',
            'password_confirmation' => 'min:6',
            'region' => 'required',
        ]);

        User::create([
            'email' => $input['email'],
            'name' => $input['username'],
            'password' => bcrypt($input['password']),
            'region' => $input['region'],
            'active' => false,
            'role' => User::ROLE_STUDENT
        ]);

        return redirect()->route('main-wait-moderator');
    }

    public function check(Request $request)
    {
        $input = $request->all();
        $this->validate($request, [
            'login_email' => 'required|email',
            'login_password' => 'required',
        ]);

        if(auth()->attempt(array('email' => $input['login_email'], 'password' => $input['login_password']),true))
        {
            if (auth()->user()->role == 'admin') {
                return redirect()->route('dashboard');
            }elseif (auth()->user()->role == 'student') {
                if (!auth()->user()->active){
                    auth()->logout();
                    return redirect()->route('main-wait-moderator');
                }
                return redirect()->route('student-courses');
            }elseif (auth()->user()->role == 'instructor') {
                return redirect()->route('instructor-dashboard');
            }
        }else{
            return redirect()->route('main-login-register')->with('error_login', 'Password or email is incorrect');
        }

    }
}

app/Http/Controllers/Main/MainController.php
<?php


namespace App\Http\Controllers\Main;


use App;
use App\Http\Controllers\Controller;
use App\Models\Career;
use App\Models\Courses;
use App\Models\Events;
use App\Models\Menu;
use App\Models\News;
use App\Models\User;
use File;
use Illuminate\Http\Client\Response;
use Request;

class MainController extends Controller
{
    public function main()
    {
        $news = News::select("*")
            ->where('name_' . $this->lang, '!=', null)
            ->where('active', 1)
            ->orderBy('date', 'desc')
            ->limit(6)
            ->get();

        $events = Events::where('name_' . $this->lang, '!=', null)
            ->where('active', 1)
//            ->where('start_date', '>', now())
            ->orderBy('start_date', 'asc')
            ->limit(4)
            ->get();
        return view('Main.main', [
            'news' => $news,
            'events' => $events
        ]);
    }

    public function generate(Request $request, string $slug)
    {
        return view('Main.generate', [
            'content' => Menu::where('link', '=', $slug)->firstOrFail()
        ]);
    }

    public function cert(User $user, Courses $course) {
        return view('Main.certificate.index', [
            'user' => $user,
            'course' => $course
        ]);
    }

    public function career(){
        $model = Career::query()->with('group')->where('parent_id', '=', 0)->get()->sortBy(function ($model) {
            return $model->group->getName();
        })->groupBy(function ($model) {
            return $model->group->getName();
        })->sortBy('name_' . \app()->getLocale());


        return view('Main.others.career',[
            'model' => $model
        ]);
    }

    public function getCareer(Career $career){
        return $career->{'content_'. app()->getLocale()};
    }
}

app/Http/Controllers/Main/NewsController.php
<?php


namespace App\Http\Controllers\Main;


use App;
use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class NewsController extends Controller
{
    public function index(Request $request)
    {
        return view('Main.news.index', [
            'model' => News::where([
                ['active', true],
                ['name_' . App::getLocale(), '!=', null],
            ])->orderBy('date','desc')->paginate(6)
        ]);
    }

    public function show(Request $request, News $news)
    {
        $news->views = $news->views + 1;
        $news->save();
        return view('Main.news.show', [
            'news' => $news
        ]);
    }

}

app/Http/Controllers/Main/ProjectsController.php
<?php


namespace App\Http\Controllers\Main;


use App;
use App\Http\Controllers\Controller;
use App\Models\Menu;
use App\Models\News;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class ProjectsController extends Controller
{
    public function atlas(Request $request)
    {
        return view('Main.projects.atlas', [
            'model' => Menu::where('link', '=', 'tourist_atlas')->firstOrFail()
        ]);
    }

}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/Main/generate.blade.php
@extends('Main.layout')
@section('title', $content->{'name_' . app()->getLocale()})
@section('breadcrumb')
    @include('Main.includes.breadcrumb', [
        'title' => $content->{'name_' . app()->getLocale()},
        'items' => [
                   "{$content->{'name_' . app()->getLocale()}}" => '',

        ]
    ])
@endsection
@section('content')

        {!! $content->{'content_' .  app()->getLocale() } !!}
@endsection

resources/views/Main/layout.blade.php
@extends('Main.main-layout')
@section('main-content')
    <section class="section-70 section-md-114">
        <div class="shell">
            <div class="range range-xs-center">
                <div class="cell-sm-8 cell-md-8 text-md-left">
                    @yield('content')
                </div>
                <div class="cell-md-4 text-left cell-xs-8 offset-top-85 offset-md-top-0">
                    <aside class="inset-md-left-30">
                        @include('Main.includes.sidebar')
                    </aside>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Main/main-layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="@yield('keywords')">
    <meta name="description" content="@yield('description')">
    <meta property="og:title" content="@yield('title')">
    <meta property="og:image" content="@yield('image')">
    <meta property="og:image:width" content="900">
    <meta property="og:image:height" content="470">
    <meta property="og:url" content="@yield('url')">
    <meta property="og:site_name" content="Tridm.uz">
    <meta property="og:type" content="@yield('type')">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="@yield('title')">
    <meta property="twitter:description" content="@yield('description')">
    <meta property="twitter:image" content="@yield('image')">
    <meta property="twitter:url" content="@yield('url')">
    <meta name="title" content="@yield('title')">
    <title>@yield('title')</title>

    <link rel="stylesheet" href="{{ asset('css/main/style.css') }}">
    <link href="{{ asset('images/other/gerb1.png') }}" rel="icon">
</head>
<body>
<!-- Page-->
<div class="page text-center">
    <!-- Page Header-->
@include('Main.includes.header')
<!-- Page Content-->
    @if(!request()->is('/'))
    @yield('breadcrumb')
    @endif
    <main class="page-content">
        @yield('main-content')
    </main>
    <!-- Corporate footer-->
    <footer class="page-footer">
        <div class="shell-wide">
            <div class="hr bg-gray-light"></div>
        </div>
        <div class="shell section-60">
            <div class="range range-lg-justify range-xs-center">
                <div class="cell-md-3 cell-lg-3">
                    <!--Footer brand--><a class="reveal-inline-block" href="/"><img width='170' height='140'
                                                                                    src='{{ asset('images/other/институт развития туризма лого.png') }}'
                                                                                    alt=''/>
                        <div>
                            <h6 class="barnd-name text-bold offset-top-25">{{ __('messages.Scientific research institute for the study of the problems of cultural heritage objects and tourism development') }}</h6>
                        </div>
                        <div>
                            <p class="brand-slogan text-gray text-italic font-accent">{{ __('messages.under the Ministry of Tourism and cultural heritage of the Republic of Uzbekistan') }}</p>
                        </div>
                    </a>
                </div>
                <div class="cell-xs-10 cell-md-5 cell-lg-4 text-lg-left offset-top-50 offset-md-top-0">
                    <h6 class="text-bold">{{ __('menu.Contacts') }}</h6>
                    <div class="text-subline"></div>
                    <div class="offset-top-30">
                        <ul class="list-unstyled contact-info list">
                            <li>
                                <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                                    <div class="unit-left"><span
                                            class="icon mdi mdi-phone text-middle icon-xs text-madison"></span></div>
                                    <div class="unit-body">
                                        <a class="text-dark" href="tel:+998712687371">+99871 268-73-71,</a>
                                        <a class="text-dark reveal-block reveal-md-inline-block"
                                           href="tel:+998712687367">+99871 268-73-67,</a>
                                        <a class="text-dark reveal-block reveal-md-inline-block"
                                           href="tel:+998712680025">+99871 268-00-25</a>
                                    </div>
                                </div>
                            </li>
                            <li class="offset-top-15">
                                <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                                    <div class="unit-left"><span
                                            class="icon mdi mdi-map-marker text-middle icon-xs text-madison"></span>
                                    </div>
                                    <div class="unit-body text-left"><a class="text-dark"
                                                                        href="#">{{ __('messages.self address') }}</a>
                                    </div>
                                </div>
                            </li>
                            <li class="offset-top-15">
                                <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                                    <div class="unit-left"><span
                                            class="icon mdi mdi-email-open text-middle icon-xs text-madison"></span>
                                    </div>
                                    <div class="unit-body"><a href="mailto:info@tridm.uz">info@tridm.uz</a></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="offset-top-15 text-left">
                        <ul class="list-inline list-inline-xs list-inline-madison">
                            <li><a class="icon icon-xxs fa-facebook icon-circle icon-gray-light-filled" target="_blank"
                                   href="https://www.facebook.com/tridm.uz/"></a></li>
                            {{--                                <li><a class="icon icon-xxs fa-twitter icon-circle icon-gray-light-filled" href="#"></a></li>--}}
                            {{--                                <li><a class="icon icon-xxs fa-google icon-circle icon-gray-light-filled" href="#"></a></li>--}}
                                                            <li><a class="icon icon-xxs fa-instagram icon-circle icon-gray-light-filled" target="_blank" href="https://www.instagram.com/tourism_development_institute/"></a></li>
                                                            <li><a class="icon icon-xxs fa-youtube-play icon-circle icon-gray-light-filled" target="_blank" href="https://www.youtube.com/channel/UCVa0pTUO2nvqV5d31LWGxwQ"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="cell-xs-10 cell-md-8 cell-lg-4 text-lg-left offset-top-50 offset-lg-top-0">
                    <h6 class="text-bold">{{ __('messages.Newsletter') }}</h6>
                    <div class="text-subline"></div>
                    <div class="offset-top-30 text-left">
                        <p>{{ __('messages.Enter your email address to receive the latest Tourism Development Institute news') }}</p>
                    </div>
                    <div class="offset-top-10">
                        <form class="rd-mailform form-subscribe" data-form-output="form-subscribe-footer"
                              data-form-type="subscribe" method="post" action="#">
                            <div class="form-group">
                                <div class="input-group input-group-sm">
                                    <input class="form-control" placeholder="{{ __('messages.Your email') }}"
                                           type="email" name="email" data-constraints="@Required @Email"/><span
                                        class="input-group-btn">
                        <button class="btn btn-sm btn-primary"
                                type="submit">{{ __('messages.Subscribe') }}</button></span>
                                </div>
                            </div>
                            <div class="form-output" id="form-subscribe-footer"></div>
                        </form>
                        <IMG height=31 src="https://cnt0.www.uz/counter/collect?id=46488&pg=http%3A//uzinfocom.uz&&col=F49918&amp;t=ffffff&amp;p=008ACC" width=88 border=0 alt="Топ рейтинг www.uz" style="float: right">
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-madison context-dark">
            <div class="shell text-md-left section-5">
                <p>&copy; <span id="copyright-year"></span></p>
            </div>
        </div>
    </footer>
</div>
<!-- Global Mailform Output-->
<div class="snackbars" id="form-output-global"></div>
<!-- Java script-->
<script src="{{ asset('js/main/core.min.js') }}"></script>
<script src="{{ asset('js/main/script.js') }}"></script>
<!-- START WWW.UZ TOP-RATING -->
<SCRIPT language="javascript" type="text/javascript">
    top_js="1.0";top_r="id=46488&r="+escape(document.referrer)+"&pg="+escape(window.location.href);document.cookie="smart_top=1; path=/"; top_r+="&c="+(document.cookie?"Y":"N")
</SCRIPT>
<SCRIPT language="javascript1.1" type="text/javascript">
    top_js="1.1";top_r+="&j="+(navigator.javaEnabled()?"Y":"N")
</SCRIPT>
<SCRIPT language="javascript1.2" type="text/javascript">
    top_js="1.2";top_r+="&wh="+screen.width+'x'+screen.height+"&px="+
        (((navigator.appName.substring(0,3)=="Mic"))?screen.colorDepth:screen.pixelDepth)
</SCRIPT>
<SCRIPT language="javascript1.3" type="text/javascript">
    top_js="1.3";
</SCRIPT>
<SCRIPT language="JavaScript" type="text/javascript">
    top_rat="&col=F49918&t=ffffff&p=008ACC";top_r+="&js="+top_js+"";document.write('<a href="http://www.uz/ru/res/visitor/index?id=46488" target=_top><img src="https://cnt0.www.uz/counter/collect?'+top_r+top_rat+'" width=88 height=31 style="display:none;" border=0 alt="Топ рейтинг www.uz"></a>')//-->
</SCRIPT><NOSCRIPT><IMG height=0 src="https://cnt0.www.uz/counter/collect?id=46488&pg=http%3A//uzinfocom.uz&&col=F49918&amp;t=ffffff&amp;p=008ACC" width=0 border=0 alt="Топ рейтинг www.uz" style="display: none"></NOSCRIPT><!-- FINISH WWW.UZ TOP-RATING -->
@yield('js_after')
</body>
</html>

resources/views/Main/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/Main/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>